"""Run state management.

Each run lives at runs/<run_id>/ with:
  config.json       — run-level config (objective, workflow, constraints)
  iterations/NNNN.json — one file per iteration with candidates + scores
  plots/, report.html — generated by viz.build_report
"""
from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import click

ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = ROOT / "runs"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def run_dir(run_id: str) -> Path:
    return RUNS_DIR / run_id


def iter_path(run_id: str, n: int) -> Path:
    return run_dir(run_id) / "iterations" / f"{n:04d}.json"


def load_config(run_id: str) -> dict[str, Any]:
    p = run_dir(run_id) / "config.json"
    if not p.exists():
        raise FileNotFoundError(f"No config at {p}. Run `rowan-state init` first.")
    return json.loads(p.read_text())


def _atomic_write_json(p: Path, data: dict[str, Any]) -> None:
    """Write JSON with an atomic replace so readers never see partial state."""
    p.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=p.parent,
        prefix=f".{p.name}.",
        suffix=".tmp",
    )
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, p)
    finally:
        tmp.unlink(missing_ok=True)


def save_config(run_id: str, cfg: dict[str, Any]) -> None:
    p = run_dir(run_id) / "config.json"
    _atomic_write_json(p, cfg)


def list_iterations(run_id: str) -> list[int]:
    d = run_dir(run_id) / "iterations"
    if not d.exists():
        return []
    nums = []
    for p in d.glob("*.json"):
        m = re.match(r"(\d+)\.json$", p.name)
        if m:
            nums.append(int(m.group(1)))
    return sorted(nums)


def load_iter(run_id: str, n: int) -> dict[str, Any]:
    return json.loads(iter_path(run_id, n).read_text())


def save_iter(run_id: str, n: int, data: dict[str, Any]) -> None:
    _atomic_write_json(iter_path(run_id, n), data)


def reserve_iter(run_id: str, data: dict[str, Any]) -> int:
    """Atomically reserve and create the next iteration number.

    Sidecar reservation files prevent concurrent score processes from choosing
    the same number. A process that dies while reserving may leave a harmless
    gap; iteration consumers already support non-contiguous numbering.
    """
    iterations_dir = run_dir(run_id) / "iterations"
    iterations_dir.mkdir(parents=True, exist_ok=True)
    existing = list_iterations(run_id)
    n = (max(existing) + 1) if existing else 1

    while True:
        reservation = iterations_dir / f".{n:04d}.reserve"
        try:
            fd = os.open(reservation, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644)
        except FileExistsError:
            n += 1
            continue

        os.close(fd)
        try:
            target = iter_path(run_id, n)
            if target.exists():
                n += 1
                continue
            record = dict(data)
            record["iter"] = n
            _atomic_write_json(target, record)
            return n
        finally:
            reservation.unlink(missing_ok=True)


def parse_jsonish(value: str) -> Any:
    """Parse CLI values as JSON when possible, falling back to strings."""
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        pass
    try:
        return float(value)
    except ValueError:
        return value


def parse_key_value_options(values: tuple[str, ...], option_name: str) -> dict[str, Any]:
    parsed: dict[str, Any] = {}
    for item in values:
        if "=" not in item:
            raise click.ClickException(f"Bad {option_name} {item!r}; expected key=value")
        key, value = item.split("=", 1)
        parsed[key] = parse_jsonish(value)
    return parsed


def all_candidates(run_id: str) -> list[dict[str, Any]]:
    """Flat list of every scored candidate across all iterations."""
    out = []
    for n in list_iterations(run_id):
        it = load_iter(run_id, n)
        for c in it.get("candidates", []):
            c2 = dict(c)
            c2["iter"] = n
            out.append(c2)
    return out


def best_so_far(run_id: str) -> dict[str, Any] | None:
    cfg = load_config(run_id)
    direction = cfg.get("objective_direction", "maximize")
    cands = [c for c in all_candidates(run_id)
             if c.get("score") is not None and c.get("satisfies_constraints", True)]
    if not cands:
        return None
    return max(cands, key=lambda c: c["score"]) if direction == "maximize" \
        else min(cands, key=lambda c: c["score"])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

@click.group()
def cli() -> None:
    """Manage Rowan autosearch run state."""


@cli.command()
@click.option("--run", "run_id", required=True, help="Short run identifier (slug).")
@click.option("--objective", required=True, help="Plain-English objective statement.")
@click.option("--direction", type=click.Choice(["maximize", "minimize"]), required=True)
@click.option("--metric", "primary_metric", required=True,
              help="Name of the primary metric this objective optimizes (e.g. logS, pKa, redox_potential).")
@click.option("--workflow", "workflow_type", required=True,
              help="Rowan workflow_type, e.g. solubility, pka, redox_potential, admet.")
@click.option("--start-smiles", required=True, help="Starting molecule SMILES.")
@click.option("--metric-path", default=None,
              help="Dot-path into object_data to find the metric value, e.g. 'solubility.logS_25C'. "
                   "If omitted, score.py will try common keys for the workflow.")
@click.option("--constraint", "constraints", multiple=True,
              help="Constraint as key=value, repeatable. e.g. mw_max=350 logp_max=4")
@click.option("--workflow-param", "workflow_params", multiple=True,
              help="Rowan workflow argument as key=json_value, repeatable. "
                   "Examples: method=\"fastsolv\", solvents='[\"water\"]', protein=\"uuid\".")
@click.option("--objective-term", "objective_terms", multiple=True,
              help="Composite objective term as JSON object, repeatable. "
                   "Example: '{\"name\":\"mw\",\"source\":\"local\",\"metric\":\"mw\",\"goal\":\"minimize\",\"weight\":0.01}'")
@click.option("--max-iter", default=50, type=int)
@click.option("--candidates-per-iter", default=4, type=int)
@click.option("--force", is_flag=True, help="Overwrite existing config.")
def init(run_id, objective, direction, primary_metric, workflow_type, start_smiles,
         metric_path, constraints, workflow_params, objective_terms, max_iter,
         candidates_per_iter, force):
    """Initialize a new run."""
    p = run_dir(run_id) / "config.json"
    if p.exists() and not force:
        raise click.ClickException(f"{p} exists. Use --force to overwrite.")

    constraint_dict = parse_key_value_options(constraints, "--constraint")
    workflow_param_dict = parse_key_value_options(workflow_params, "--workflow-param")

    parsed_objective_terms = []
    for term in objective_terms:
        value = parse_jsonish(term)
        if not isinstance(value, dict):
            raise click.ClickException(
                f"Bad --objective-term {term!r}; expected a JSON object"
            )
        parsed_objective_terms.append(value)

    cfg = {
        "run_id": run_id,
        "objective": objective,
        "objective_direction": direction,
        "primary_metric": primary_metric,
        "workflow_type": workflow_type,
        "start_smiles": start_smiles,
        "metric_path": metric_path,
        "constraints": constraint_dict,
        "max_iterations": max_iter,
        "candidates_per_iter": candidates_per_iter,
        "created_at": now_iso(),
    }
    if workflow_param_dict:
        cfg["workflow_params"] = workflow_param_dict
    if parsed_objective_terms:
        cfg["optimization_objective"] = {
            "name": primary_metric,
            "terms": parsed_objective_terms,
        }
    save_config(run_id, cfg)
    (run_dir(run_id) / "iterations").mkdir(parents=True, exist_ok=True)
    (run_dir(run_id) / "plots").mkdir(parents=True, exist_ok=True)
    click.echo(f"Initialized run {run_id} at {run_dir(run_id)}")
    click.echo(json.dumps(cfg, indent=2))


@cli.command()
@click.option("--run", "run_id", required=True)
def status(run_id):
    """Print run summary: config, iteration count, best-so-far."""
    cfg = load_config(run_id)
    iters = list_iterations(run_id)
    best = best_so_far(run_id)
    click.echo(f"Run: {run_id}")
    click.echo(f"  Objective:     {cfg['objective']}")
    click.echo(f"  Direction:     {cfg['objective_direction']} {cfg['primary_metric']}")
    click.echo(f"  Workflow:      {cfg['workflow_type']}")
    click.echo(f"  Iterations:    {len(iters)} / {cfg['max_iterations']}")
    if best:
        metric_value = best.get("metrics", {}).get(cfg["primary_metric"], best["score"])
        click.echo(f"  Best so far:   {best['smiles']}  ({cfg['primary_metric']}={metric_value})")
        click.echo(f"  Found at iter: {best['iter']}")
    else:
        click.echo("  Best so far:   (none yet)")


@cli.command(name="list")
def list_runs():
    """List all runs."""
    if not RUNS_DIR.exists():
        click.echo("No runs yet.")
        return
    for d in sorted(RUNS_DIR.iterdir()):
        if (d / "config.json").exists():
            cfg = json.loads((d / "config.json").read_text())
            n = len(list_iterations(d.name))
            click.echo(f"  {d.name:30s}  iter={n:3d}  obj={cfg['objective'][:60]}")


if __name__ == "__main__":
    cli()
